# Generated by Django 2.0.4 on 2018-09-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('username',)},
        ),
    ]
