# Generated by Django 2.0.4 on 2018-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20180214_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
